### ISSUE TITLE
`GLIBC_2.32' not found in Gogle Colab 

### ISSUE THREAD

**Issue by rekil156** [mme/langforge#2]
Hi, i was trying it out on Google colab and when i run - 
`!langforge create myapp` 
i get the following error- 
`/usr/local/lib/python3.9/dist-packages/langforge/bin/langforge-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/lib/python3.9/dist-packages/langforge/bin/langforge-linux-amd64)
/usr/local/lib/python3.9/dist-packages/langforge/bin/langforge-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/lib/python3.9/dist-packages/langforge/bin/langforge-linux-amd64)
`
Any suggestions
Python 3.9.16

**Comment by mme** [comment]
Probably related:

https://github.com/golang/go/issues/58550
https://github.com/golang/go/issues/57328

**Comment by mme** [comment]
I'm afraid you can't run `langforge create` yet from within jupyterlab/colab since it needs a real terminal.

Can you give me more background on your use case? 

Helps me better understand what you want to achieve 😎

**Comment by rekil156** [comment]
Ah I see that is fine, i'm not committed to using jupyterlab/colab. I'll try it out with a real terminal. Thanks for responding so quickly :)
